name: app_plantas_medicinales
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.2
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.6.1
  liquid_swipe: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  animate_do: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  
  
  

  #page_transition
  # page_transtion: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  #change_app_package_name : ^ 1.1.0
  flutter_native_splash: ^2.1.1
  flutter_lints: ^1.0.0
  


#Run comands to generate splash screen
#1) flutter clean
#2) flutter pub get
#3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "lib/assets/imagenes/splash_image.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  
  


flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - lib/assets/
  - lib/assets/tratamientosimg/
  - lib/assets/artrosis/
  - lib/assets/angina/
  - lib/assets/anemia/
  - lib/assets/alimentacion/
  - lib/assets/afonico/
  - lib/assets/absceso/
  - lib/assets/acne/
  - lib/assets/acercade/
  - lib/assets/ajenjo/
  - lib/assets/albahacar/
  - lib/assets/aceitilla/
  - lib/assets/ajo/
  - lib/assets/ahuehuete/
  - lib/assets/artemisa/
  - lib/assets/anis/
  - lib/assets/apio/
  - lib/assets/B/berro/
  - lib/assets/B/bugambilia/
  - lib/assets/B/Candelilla/
  - lib/assets/C/capulin/
  - lib/assets/C/Cardo_Mariano/
  - lib/assets/C/Cardo_Santo/
  - lib/assets/C/Cebolla/
  - lib/assets/C/Cempasuchil/
  - lib/assets/C/Chaya/
  - lib/assets/C/Chicalote/
  - lib/assets/C/Cipres_Comun/
  - lib/assets/C/Cola_de_Caballo/
  - lib/assets/C/Contrahierba/
  - lib/assets/D/
  - lib/assets/F/
  - lib/assets/G/
  - lib/assets/H/
  - lib/assets/M/
  - lib/assets/P/
  - lib/assets/T/
  - lib/assets/imagenes/

  fonts:
  #  - family: Klasik
  #    fonts:
  #      - asset: lib/assets/fonts/Klasik Regular.otf
    - family: RobotoSlab
      fonts:
        - asset: lib/assets/fonts/RobotoSlab-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
